# Learn all the formats of Wikipedia scrapping

In [1]:
#!pip install requests

Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (1.26.9)

In [5]:
#!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)

In [2]:
# import modules
import requests
from bs4 import BeautifulSoup

In [4]:
url = 'https://en.wikipedia.org/wiki/Mahatma_Gandhi'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
response = requests.get(url, headers=headers)
#print(response.status_code)

200

In [6]:
# soup = BeautifulSoup(response.content, 'html.parser')

# title = soup.find(id="firstHeading")
# print(title.string)

Mahatma Gandhi

## Finding all the hyperlinks of a wikipedia page

In [48]:
allLinks = soup.find(id="bodyContent").find_all("a")
linkToScrape = []
for link in allLinks:
    if link.get('href') is not None and link.get('href').find("/wiki/")== 0: 
        linkToScrape.append(link)

print(len(linkToScrape))
# print the urls of linkToScrape
# https://en.wikipedia.org/wiki/Nationalism#Anti-colonial_nationalism
url = "https://en.wikipedia.org"
urls = []
for link in linkToScrape:
    urls.append(url+link['href'])
print(urls)

3529

In [51]:
with open('scrapped_gandhi_links.txt','w') as f:
    f.write('\n'.join(urls))

## Fetching all the paragraphs of wikipedia page

In [8]:
url = 'https://simple.wikipedia.org/wiki/Mahatma_Gandhi'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.content, 'html.parser') 
list(soup.children)
 
for i in range(len(soup.find_all('p'))):
    print(soup.find_all('p')[i].get_text())
    print('\n\n')

				Pages for logged out editors learn more




Mohandas Karamchand Gandhi (/ˈɡɑːndi, ˈɡændi/;[2] GAHN-dee; 2 October 1869 – 30 January 1948) was a leader of nationalism in British-ruled India. He is more commonly called Mahatma Gandhi;[3] mahatma is an honorific meaning "great-soul" or "venerable" in Sanskrit. He was first called this in 1914 in South Africa. He is also called Bapu in India (Gujarati endearment for "father", "papa").




He was the Martyr of the Nation since 1948. Rabindranath Tagore gave him the title of  'Mahatma'.[4]




Gandhi was one of the most important people involved in the movement for the independence of India. He was a non-violent activist, who led the independence movement through a non-violent protest.




Mohandas Karamchand Gandhi was born on October 2, 1869 in Porbandar, India.[5]  Several members of his family worked for the government of the state.  When Gandhi was 18 years old, he went to study law in England.[6]  After he became a lawyer, he went to the British colony of South Africa where he experienced laws that said people with  dark  skin had fewer rights than people with light skin. In 1897, Gandhi was attacked by a group of people in Durban Harbor, South Africa when he was going to work. He went to South Africa because he could not find work in India.[7] When traveling through South Africa, Gandhi was also kicked out of a first class train because of his skin color. Then Gandhi started protesting against segregation.[8] He decided then to become a political activist, so he could help change these unfair laws.  He created a powerful, non-violent movement. During Gandhi's life, India was a colony of the British Empire, but wanted independence.  He was a huge leader during that era and his thoughts helped catalyze the Indian independence movement.




Gandhi was a vegetarian almost all his life, because he believed in non-violence (ahimsa).[9]




On 9 January 1915 when Gandhi returned to India, he decided to again lead a march against a law called the Rowlatt Act. But then the protest turned violent and people started to kill the protesters.[8]




On 12 March 1930 Gandhi led the Salt March.




When he returned to India, he helped cause India's independence from British rule, inspiring other colonial people to work for their independence, break up the British Empire, and replace it with the Commonwealth.




People of many different religions and ethnic groups lived in British India. Many people thought the country should break into separate countries so different groups could have their own countries. In particular, many people thought that Hindus and Muslims should have separate countries. Gandhi was a Hindu, but he liked ideas from many religions including Islam, Judaism, and Christianity, and he thought that people of all religions should have the same rights, and could live together peacefully in the same country.




In 1938, Gandhi resigned from Congress. He said he could no longer work through Congress to unite the divisions in caste and religion. He also felt that he had little to offer to the political process.[10]




On 15 August 1947, the British Indian Empire split into India and Pakistan. Gandhi wanted independence but did not want the former Raj to split into two different countries. Instead of celebrating independence day, he was crying over the end of British India.




Gandhi's principle of satyagraha, often translated as "way of truth" or "pursuit of truth", has inspired other democratic and anti-racist activists like Martin Luther King, Jr. and Nelson Mandela. Gandhi often said that his values were simple, based upon traditional Hindu beliefs: truth (Satya), and non-violence (ahimsa).




On January 30, 1948, he was shot to death by a Brahman activist Nathuram Godse, because Godse thought that Gandhi was too respectful to the Muslims. Godse was tried and executed by Indian officials.

## Working with wikipedia tables

In [10]:
import pandas as pd
url = "https://en.wikipedia.org/wiki/1999%E2%80%932000_FA_Premier_League"
tables = pd.read_html(url) 
print(tables)
tables[3]

[    0                                                  1
0 NaN  This article includes a list of general refere...,                        0                                                  1
0                 Season                                          1999–2000
1                  Dates                        7 August 1999 – 14 May 2000
2              Champions  Manchester United6th Premier League title13th ...
3              Relegated                WimbledonSheffield WednesdayWatford
4       Champions League               Manchester UnitedArsenalLeeds United
5               UEFA Cup                     LiverpoolChelseaLeicester City
6          Intertoto Cup                           Aston VillaBradford City
7         Matches played                                                380
8           Goals scored                             1,060 (2.79 per match)
9         Top goalscorer                          Kevin Phillips (30 goals)
10      Biggest home win  Newcastle United 8–0 Sheffield Wednesday(19 Se...
11      Biggest away win     Derby County 0–5 Sunderland(18 September 1999)
12       Highest scoring  West Ham United 5–4 Bradford City(12 February ...
13   Longest winning run                       11 games[1]Manchester United
14  Longest unbeaten run                                 16 games[1]Chelsea
15   Longest winless run                       11 games[1]SunderlandWatford
16    Longest losing run                                8 games[1]Wimbledon
17    Highest attendance  61,619Manchester United v Derby County(11 Marc...
18     Lowest attendance  8,248Wimbledon v Sheffield Wednesday(12 April ...
19    Average attendance                                              30755
20   ← 1998–99 2000–01 →                                ← 1998–99 2000–01 →,                    Team             Location               Stadium  Capacity
0               Arsenal    London (Highbury)       Arsenal Stadium     38419
1           Aston Villa           Birmingham            Villa Park     42573
2         Bradford City             Bradford         Valley Parade     25136
3               Chelsea      London (Fulham)       Stamford Bridge     42055
4         Coventry City             Coventry        Highfield Road     23489
5          Derby County                Derby    Pride Park Stadium     33597
6               Everton   Liverpool (Walton)         Goodison Park     40569
7          Leeds United                Leeds           Elland Road     40242
8        Leicester City            Leicester        Filbert Street     22000
9             Liverpool  Liverpool (Anfield)               Anfield     45522
10    Manchester United           Manchester          Old Trafford     68174
11        Middlesbrough        Middlesbrough     Riverside Stadium     35049
12     Newcastle United  Newcastle upon Tyne        St James' Park     52387
13  Sheffield Wednesday            Sheffield  Hillsborough Stadium     39732
14          Southampton          Southampton              The Dell     15200
15           Sunderland           Sunderland      Stadium of Light     49000
16    Tottenham Hotspur   London (Tottenham)       White Hart Lane     36240
17              Watford              Watford         Vicarage Road     19920
18      West Ham United  London (Upton Park)         Boleyn Ground     35647
19            Wimbledon    London (Selhurst)      Selhurst Park[a]     26074,                    Team                     Manager           Captain  \
0               Arsenal               Arsène Wenger        Tony Adams
1           Aston Villa                John Gregory  Gareth Southgate
2         Bradford City                 Paul Jewell     Stuart McCall
3               Chelsea             Gianluca Vialli       Dennis Wise
4         Coventry City             Gordon Strachan   Gary McAllister
5          Derby County                   Jim Smith     Darryl Powell
6               Everton                Walter Smith       Dave Watson
7          Leeds United               David O'Leary      Lucas Radebe
8        Leicester City              Martin O'Neill      Matt Elliott
9             Liverpool             Gérard Houllier    Jamie Redknapp
10    Manchester United           Sir Alex Ferguson         Roy Keane
11        Middlesbrough                Bryan Robson         Paul Ince
12     Newcastle United                Bobby Robson      Alan Shearer
13  Sheffield Wednesday  Peter Shreeves (caretaker)        Des Walker
14          Southampton                Glenn Hoddle   Matt Le Tissier
15           Sunderland                  Peter Reid       Steve Bould
16    Tottenham Hotspur               George Graham      Sol Campbell
17              Watford               Graham Taylor          Rob Page
18      West Ham United              Harry Redknapp       Steve Lomas
19            Wimbledon                Terry Burton      Robbie Earle

   Kit manufacturer        Shirt sponsor
0              Nike       Dreamcast/Sega
1            Reebok             LDV Vans
2             Asics               JCT600
3             Umbro            Autoglass
4     CCFC Garments               Subaru
5              Puma                  EDS
6             Umbro              One2One
7              Puma         Packard Bell
8       Fox Leisure       Walkers Crisps
9            Reebok      Carlsberg Group
10            Umbro                Sharp
11            Erreà           BT Cellnet
12           Adidas  Newcastle Brown Ale
13             Puma            Sanderson
14           Saints    Friends Provident
15            Asics            Reg Vardy
16           Adidas              Holsten
17   Le Coq Sportif             Phones4U
18             Fila          Dr. Martens
19            Lotto                 Tiny  ,                   Team Outgoing manager  Manner of departure  \
0            Wimbledon      Joe Kinnear             Resigned
1     Newcastle United      Ruud Gullit             Resigned
2          Southampton       Dave Jones  Contract terminated
3  Sheffield Wednesday     Danny Wilson               Sacked
4            Wimbledon       Egil Olsen               Sacked

      Date of vacancy Position in table            Incoming manager  \
0         9 June 1999        Pre-season                  Egil Olsen
1   28 August 1999[2]              19th                Bobby Robson
2  27 January 2000[a]              17th                Glenn Hoddle
3    21 March 2000[4]              19th  Peter Shreeves (caretaker)
4       1 May 2000[5]              18th                Terry Burton

   Date of appointment
0          9 June 1999
1  2 September 1999[3]
2      28 January 2000
3        21 March 2000
4           1 May 2000  ,     Pos                     Team  Pld   W   D   L  GF  GA   GD  Pts  \
0     1    Manchester United (C)   38  28   7   3  97  45  +52   91
1     2                  Arsenal   38  22   7   9  73  43  +30   73
2     3             Leeds United   38  21   6  11  58  43  +15   69
3     4                Liverpool   38  19  10   9  51  30  +21   67
4     5                  Chelsea   38  18  11   9  53  34  +19   65
5     6              Aston Villa   38  15  13  10  46  35  +11   58
6     7               Sunderland   38  16  10  12  57  56   +1   58
7     8           Leicester City   38  16   7  15  55  55    0   55
8     9          West Ham United   38  15  10  13  52  53   −1   55
9    10        Tottenham Hotspur   38  15   8  15  57  49   +8   53
10   11         Newcastle United   38  14  10  14  63  54   +9   52
11   12            Middlesbrough   38  14  10  14  46  52   −6   52
12   13                  Everton   38  12  14  12  59  49  +10   50
13   14            Coventry City   38  12   8  18  47  54   −7   44
14   15              Southampton   38  12   8  18  45  62  −17   44
15   16             Derby County   38   9  11  18  44  57  −13   38
16   17            Bradford City   38   9   9  20  38  68  −30   36
17   18            Wimbledon (R)   38   7  12  19  46  74  −28   33
18   19  Sheffield Wednesday (R)   38   8   7  23  38  70  −32   31
19   20              Watford (R)   38   6   6  26  35  77  −42   24

                          Qualification or relegation
0   Qualification for the Champions League first g...
1   Qualification for the Champions League first g...
2   Qualification for the Champions League third q...
3       Qualification for the UEFA Cup first round[a]
4       Qualification for the UEFA Cup first round[a]
5     Qualification for the Intertoto Cup third round
6                                                 NaN
7       Qualification for the UEFA Cup first round[b]
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16   Qualification for the Intertoto Cup second round
17   Relegation to the Football League First Division
18   Relegation to the Football League First Division
19   Relegation to the Football League First Division  ,             Home \ Away  ARS  AVL  BRA  CHE  COV  DER  EVE  LEE  LEI  ...  \
0               Arsenal  NaN  3–1  2–0  2–1  3–0  2–1  4–1  2–0  2–1  ...
1           Aston Villa  1–1  NaN  1–0  0–0  1–0  2–0  3–0  1–0  2–2  ...
2         Bradford City  2–1  1–1  NaN  1–1  1–1  4–4  0–0  1–2  3–1  ...
3               Chelsea  2–3  1–0  1–0  NaN  2–1  4–0  1–1  0–2  1–1  ...
4         Coventry City  3–2  2–1  4–0  2–2  NaN  2–0  1–0  3–4  0–1  ...
5          Derby County  1–2  0–2  0–1  3–1  0–0  NaN  1–0  0–1  3–0  ...
6               Everton  0–1  0–0  4–0  1–1  1–1  2–1  NaN  4–4  2–2  ...
7          Leeds United  0–4  1–2  2–1  0–1  3–0  0–0  1–1  NaN  2–1  ...
8        Leicester City  0–3  3–1  3–0  2–2  1–0  0–1  1–1  2–1  NaN  ...
9             Liverpool  2–0  0–0  3–1  1–0  2–0  2–0  0–1  3–1  0–2  ...
10    Manchester United  1–1  3–0  4–0  3–2  3–2  3–1  5–1  2–0  2–0  ...
11        Middlesbrough  2–1  0–4  0–1  0–1  2–0  1–4  2–1  0–0  0–3  ...
12     Newcastle United  4–2  0–1  2–0  0–1  2–0  2–0  1–1  2–2  0–2  ...
13  Sheffield Wednesday  1–1  0–1  2–0  1–0  0–0  0–2  0–2  0–3  4–0  ...
14          Southampton  0–1  2–0  1–0  1–2  0–0  3–3  2–0  0–3  1–2  ...
15           Sunderland  0–0  2–1  0–1  4–1  1–1  1–1  2–1  1–2  2–0  ...
16    Tottenham Hotspur  2–1  2–4  1–1  0–1  3–2  1–1  3–2  1–2  2–3  ...
17              Watford  2–3  0–1  1–0  1–0  1–0  0–0  1–3  1–2  1–1  ...
18      West Ham United  2–1  1–1  5–4  0–0  5–0  1–1  0–4  0–0  2–1  ...
19            Wimbledon  1–3  2–2  3–2  0–1  1–1  2–2  0–3  2–0  2–1  ...

    MUN  MID  NEW  SHW  SOU  SUN  TOT  WAT  WHU  WIM
0   1–2  5–1  0–0  3–3  3–1  4–1  2–1  1–0  2–1  1–1
1   0–1  1–0  0–1  2–1  0–1  1–1  1–1  4–0  2–2  1–1
2   0–4  1–1  2–0  1–1  1–2  0–4  1–1  3–2  0–3  3–0
3   5–0  1–1  1–0  3–0  1–1  4–0  1–0  2–1  0–0  3–1
4   1–2  2–1  4–1  4–1  0–1  3–2  0–1  4–0  1–0  2–0
5   1–2  1–3  0–0  3–3  2–0  0–5  0–1  2–0  1–2  4–0
6   1–1  0–2  0–2  1–1  4–1  5–0  2–2  4–2  1–0  4–0
7   0–1  2–0  3–2  2–0  1–0  2–1  1–0  3–1  1–0  4–1
8   0–2  2–1  1–2  3–0  2–1  5–2  0–1  1–0  1–3  2–1
9   2–3  0–0  2–1  4–1  0–0  1–1  2–0  0–1  1–0  3–1
10  NaN  1–0  5–1  4–0  3–3  4–0  3–1  4–1  7–1  1–1
11  3–4  NaN  2–2  1–0  3–2  1–1  2–1  1–1  2–0  0–0
12  3–0  2–1  NaN  8–0  5–0  1–2  2–1  1–0  2–2  3–3
13  0–1  1–0  0–2  NaN  0–1  0–2  1–2  2–2  3–1  5–1
14  1–3  1–1  4–2  2–0  NaN  1–2  0–1  2–0  2–1  2–0
15  2–2  1–1  2–2  1–0  2–0  NaN  2–1  2–0  1–0  2–1
16  3–1  2–3  3–1  0–1  7–2  3–1  NaN  4–0  0–0  2–0
17  2–3  1–3  1–1  1–0  3–2  2–3  1–1  NaN  1–2  2–3
18  2–4  0–1  2–1  4–3  2–0  1–1  1–0  1–0  NaN  2–1
19  2–2  2–3  2–0  0–2  1–1  1–0  1–1  5–0  2–2  NaN

[20 rows x 21 columns],    Rank           Player               Club  Goals
0     1   Kevin Phillips         Sunderland     30
1     2     Alan Shearer   Newcastle United     23
2     3     Dwight Yorke  Manchester United     20
3     4  Michael Bridges       Leeds United     19
4     4        Andy Cole  Manchester United     19
5     6    Thierry Henry            Arsenal     17
6     7   Paolo Di Canio    West Ham United     16
7     8  Chris Armstrong  Tottenham Hotspur     14
8     8  Steffen Iversen  Tottenham Hotspur     14
9     8      Niall Quinn         Sunderland     14,                     Player                For              Against   Result  \
0          Michael Bridges       Leeds United          Southampton  3–0 (A)
1               Andy Cole4  Manchester United     Newcastle United  5–1 (H)
2           Kevin Phillips         Sunderland         Derby County  5–0 (A)
3            Alan Shearer5   Newcastle United  Sheffield Wednesday  8–0 (H)
4             Nwankwo Kanu            Arsenal              Chelsea  3–2 (A)
5            Marc Overmars            Arsenal        Middlesbrough  5–1 (H)
6   Ole Gunnar Solskjær4 P  Manchester United              Everton  5–1 (H)
7              Nick Barmby            Everton      West Ham United  4–0 (A)
8           Stan Collymore     Leicester City           Sunderland  5–2 (H)
9          Steffen Iversen  Tottenham Hotspur          Southampton  7–2 (H)
10            Dwight Yorke  Manchester United         Derby County  3–1 (H)
11            Paul Scholes  Manchester United      West Ham United  7–1 (H)
12            Dean Windass      Bradford City         Derby County  4–4 (H)

                 Date   Ref
0      11 August 1999   [6]
1      30 August 1999   [7]
2   18 September 1999   [8]
3   19 September 1999   [9]
4     23 October 1999  [10]
5    21 November 1999  [11]
6     4 December 1999  [12]
7    26 February 2000  [13]
8        5 March 2000  [14]
9       11 March 2000  [15]
10      11 March 2000  [16]
11       1 April 2000  [17]
12      21 April 2000  [18]  ,    Rank           Player                 Club  Assists[19]
0     1    David Beckham    Manchester United           15
1     1  Nolberto Solano     Newcastle United           15
2     3   Paolo Di Canio      West Ham United           13
3     4       Ryan Giggs    Manchester United           12
4     5  Dennis Bergkamp              Arsenal            9
5     6      Nick Barmby              Everton            8
6     6    Thierry Henry              Arsenal            8
7     6  Steffen Iversen    Tottenham Hotspur            8
8     6         Wim Jonk  Sheffield Wednesday            8
9     6      Paul Merson          Aston Villa            8,        Month Manager of the Month                      Player of the Month  \
       Month              Manager                 Club              Player
0     August        Alex Ferguson    Manchester United        Robbie Keane
1  September         Walter Smith              Everton         Muzzy Izzet
2    October           Peter Reid           Sunderland      Kevin Phillips
3   November       Martin O'Neill       Leicester City         Sami Hyypiä
4   December      Gérard Houllier            Liverpool           Roy Keane
5    January         Danny Wilson  Sheffield Wednesday    Gareth Southgate
6   February         Bobby Robson     Newcastle United         Paul Merson
7      March        Alex Ferguson    Manchester United        Dwight Yorke
8      April        Alex Ferguson    Manchester United       Thierry Henry


                Club
0      Coventry City
1     Leicester City
2         Sunderland
3          Liverpool
4  Manchester United
5        Aston Villa
6        Aston Villa
7  Manchester United
8            Arsenal  ,                                   Award          Winner               Club
0  Premier League Manager of the Season   Alex Ferguson  Manchester United
1   Premier League Player of the Season  Kevin Phillips         Sunderland
2       PFA Players' Player of the Year       Roy Keane  Manchester United
3          PFA Young Player of the Year    Harry Kewell       Leeds United
4            FWA Footballer of the Year       Roy Keane  Manchester United,   PFA Team of the Year             PFA Team of the Year.1  \
0           Goalkeeper        Nigel Martyn (Leeds United)
1              Defence          Gary Kelly (Leeds United)
2             Midfield  David Beckham (Manchester United)
3               Attack      Andy Cole (Manchester United)

              PFA Team of the Year.2             PFA Team of the Year.3  \
0        Nigel Martyn (Leeds United)        Nigel Martyn (Leeds United)
1          Gary Kelly (Leeds United)          Gary Kelly (Leeds United)
2  David Beckham (Manchester United)  David Beckham (Manchester United)
3      Andy Cole (Manchester United)      Andy Cole (Manchester United)

          PFA Team of the Year.4         PFA Team of the Year.5  \
0    Nigel Martyn (Leeds United)    Nigel Martyn (Leeds United)
1  Jaap Stam (Manchester United)  Jaap Stam (Manchester United)
2  Roy Keane (Manchester United)  Roy Keane (Manchester United)
3  Andy Cole (Manchester United)  Andy Cole (Manchester United)

          PFA Team of the Year.6       PFA Team of the Year.7  \
0    Nigel Martyn (Leeds United)  Nigel Martyn (Leeds United)
1  Jaap Stam (Manchester United)      Sami Hyypiä (Liverpool)
2  Roy Keane (Manchester United)     Patrick Vieira (Arsenal)
3  Andy Cole (Manchester United)  Kevin Phillips (Sunderland)

        PFA Team of the Year.8       PFA Team of the Year.9  \
0  Nigel Martyn (Leeds United)  Nigel Martyn (Leeds United)
1      Sami Hyypiä (Liverpool)      Sami Hyypiä (Liverpool)
2     Patrick Vieira (Arsenal)     Patrick Vieira (Arsenal)
3  Kevin Phillips (Sunderland)  Kevin Phillips (Sunderland)

       PFA Team of the Year.10      PFA Team of the Year.11  \
0  Nigel Martyn (Leeds United)  Nigel Martyn (Leeds United)
1     Ian Harte (Leeds United)     Ian Harte (Leeds United)
2  Harry Kewell (Leeds United)  Harry Kewell (Leeds United)
3  Kevin Phillips (Sunderland)  Kevin Phillips (Sunderland)

       PFA Team of the Year.12
0  Nigel Martyn (Leeds United)
1     Ian Harte (Leeds United)
2  Harry Kewell (Leeds United)
3  Kevin Phillips (Sunderland)  ,   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vtePremier League  \
0                                            Seasons
1                                              Clubs
2                                            2022–23
3                                             Former
4                                        Competition
5                              Statistics and awards
6                                           Finances
7                            Associated competitions
8                                           Category


,Team,Manager,Captain,Kit manufacturer,Shirt sponsor
0,Arsenal,Arsène Wenger,Tony Adams,Nike,Dreamcast/Sega
1,Aston Villa,John Gregory,Gareth Southgate,Reebok,LDV Vans
2,Bradford City,Paul Jewell,Stuart McCall,Asics,JCT600
3,Chelsea,Gianluca Vialli,Dennis Wise,Umbro,Autoglass
4,Coventry City,Gordon Strachan,Gary McAllister,CCFC Garments,Subaru
5,Derby County,Jim Smith,Darryl Powell,Puma,EDS
6,Everton,Walter Smith,Dave Watson,Umbro,One2One
7,Leeds United,David O'Leary,Lucas Radebe,Puma,Packard Bell
8,Leicester City,Martin O'Neill,Matt Elliott,Fox Leisure,Walkers Crisps
9,Liverpool,Gérard Houllier,Jamie Redknapp,Reebok,Carlsberg Group
10,Manchester United,Sir Alex Ferguson,Roy Keane,Umbro,Sharp
11,Middlesbrough,Bryan Robson,Paul Ince,Erreà,BT Cellnet
12,Newcastle United,Bobby Robson,Alan Shearer,Adidas,Newcastle Brown Ale
13,Sheffield Wednesday,Peter Shreeves (caretaker),Des Walker,Puma,Sanderson
14,Southampton,Glenn Hoddle,Matt Le Tissier,Saints,Friends Provident
15,Sunderland,Peter Reid,Steve Bould,Asics,Reg Vardy
16,Tottenham Hotspur,George Graham,Sol Campbell,Adidas,Holsten
17,Watford,Graham Taylor,Rob Page,Le Coq Sportif,Phones4U
18,West Ham United,Harry Redknapp,Steve Lomas,Fila,Dr. Martens
19,Wimbledon,Terry Burton,Robbie Earle,Lotto,Tiny